
export const ACTION_LOGIN_BEGIN = 'ACTION_LOGIN_BEGIN';
export const ACTION_LOGIN_END = 'ACTION_LOGIN_END';
export const ACTION_LOGIN_QUIT = 'ACTION_LOGIN_QUIT';

export const ACTION_GET_USERINFO_BEGIN = 'ACTION_GET_USERINFO_BEGIN';
export const ACTION_GET_USERINFO_END = 'ACTION_GET_USERINFO_END';

export const ACTION_SET_USERINFO_BEGIN = 'ACTION_SET_USERINFO_BEGIN';
export const ACTION_SET_USERINFO_END = 'ACTION_SET_USERINFO_END';

export const ACTION_REFRESH_ADS_LIST = 'ACTION_REFRESH_ADS_LIST';
export const ACTION_REFRESH_LED_LIST = 'ACTION_REFRESH_LED_LIST';

export const ACTION_WS_OPENING = '';
export const ACTION_WS_RECEIVED = '';
export const ACTION_WS_ERROR = '';
export const ACTION_WS_CLOSED = '';